### PR TITLE
feat: Add `shirt` icon

### PR DESCRIPTION
**Pull request by lscheibel**
Screenshot:

[Preview](https://github.com/featherity/featherity/pull/20/files?short_path=639344a#diff-639344af3b34774ca3f2f1b2bd3cb6cd)

image

### CODE REVIEW

**Comment by ericfennis** [comment]
the bottom corner radius look a bit out of sync with the other corner. And if you look to the [preview](https://github.com/featherity/featherity/pull/20/files?short_path=639344a#diff-639344af3b34774ca3f2f1b2bd3cb6cd) the armpits are barely to see, did you try to shrink the body and make sleeves longer?

**Comment by lscheibel** [comment]
Shrinking the body worked quite well. The corners I think look best when viewed at 100%, here are some more versions though (all with a little narrower torso):

100%
image

Closeup
image

**Comment by ericfennis** [comment]
Oeh nice, looks awesome! And how looks A with a neck of B?

**Comment by lscheibel** [comment]
image

image


I like it too!

**Comment by ericfennis** [comment]
Nice I like that one!
What do you think @locness3 @jletey ?

**Comment by dgdavid** [comment]
Hi there!

I like E and B

**Comment by mittalyashu** [comment]
Vote for “B”

**Comment by ericfennis** [comment]
Version B it is I think?

**Comment by lscheibel** [comment]
👍 I'll see when I come around to updating the pr

**Comment by lscheibel** [comment]
New icon:

image

image

**Review by ericfennis — APPROVED** [review]

**Pull request merged**
