### PR TITLE
feat: Add `unlink` icons

### LINKED ISSUE #26: Icon request: start/stop sharing screen
Hi there!

First of all, **thank you a lot** for the initiative to, somehow, _moving forward_ the [Feather](https://github.com/feathericons/feather) project. I really hope the effort and result can convince @colebemis  about [his concerns](https://github.com/feathericons/feather/issues/893#issuecomment-617463032) and see both project meet in the near future.

That said, my request is an icon for the "Screen sharing" action in a video conferencing software. Back in April, I was trying to do it but my lack of design / SVG / Figma knowledge didn't allow me to make something presentable. Even after spending quite some hours! Quite frustrating :)

However, just in case it could be helpful, I can tell you that I don't like too much the one [included in the Material Design icons](https://material.io/resources/icons/?icon=screen_share&style=baseline). Maybe, something similar to https://thenounproject.com/search/?q=screen%20share&i=2012801 or https://thenounproject.com/tomekpst/collection/basic-icons/?i=2012799 but based the [Feather/monitor](https://feathericons.com/?query=monitor) could look nice.

On the other hand, using the [Feather/wifi](https://feathericons.com/?query=wifi) or [Feather/rss](https://feathericons.com/?query=rss) icon as part of it instead of the arrow could be confusing because it seems to be more appropriate for an "screen-casting" action, isn't it?

What do you think? Could it be possible to have _feather-style_ icons for start / stop sharing the screen?

Thanks in advance.

## Icon Request

* Icon name: start-screen-sharing, stop-screen-sharing
* Use case: for a video conferencing software
* Screenshots of similar icons:

  |||
  |-|-|
  | Screenshot_2020-06-26 Noun Project | Screenshot_2020-06-26 Noun Project(1) |

### PR DESCRIPTION
**Pull request by ericfennis**
Closes #26

### Old comment from the thread
image

For the `unlink` for the `link` variant I tried to keep the lines of the `link` icon.
So this is the link with overlayed over the original `link` icon.
image

I followed the Icon guide lines from #171. But it's hard with this one to keep the original lines of the link icon and keep exactly 2 pixels of spacing.

### CODE REVIEW

**Comment by jletey** [comment]
🤔 I'm not too sure about the `unlink-2` icon.

What do you think about this for the `unlink` icon:



unlink

```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M18.84 12.25L20.56 10.54H20.54C21.4606 9.58604 21.9651 8.30573 21.9426 6.98018C21.9201 5.65462 21.3725 4.39217 20.42 3.47C19.4869 2.57019 18.2412 2.06739 16.945 2.06739C15.6488 2.06739 14.4031 2.57019 13.47 3.47L11.75 5.18" />
  <path d="M5.17 11.75L3.46 13.46C2.53937 14.414 2.03492 15.6943 2.05742 17.0198C2.07992 18.3454 2.62752 19.6078 3.58 20.53C4.51305 21.4298 5.75876 21.9326 7.055 21.9326C8.35124 21.9326 9.59695 21.4298 10.53 20.53L12.24 18.82" />
  <path d="M8 2V5" />
  <path d="M2 8H5" />
  <path d="M16 19V22" />
  <path d="M19 16H22" />
  <path d="M19 19L21 21" />
  <path d="M3 3L5 5" />
</svg>
```

**Comment by locness3** [comment]
> What do you think about this for the unlink icon:

I personally prefer ericfennis's version, because it has less "pops"

**Comment by ericfennis** [comment]
I tried the `unlink` icon also with three strokes but It looked a bit messy to me.

#### here both side by side for comparison 

image
image

image

**Comment by ericfennis** [comment]
A suggestion from @jletey to create a `link-2-off` icon as well. (Discussed in the [discord channel](https://discord.gg/x4nJxx))
I like the idea, I think it's nice to have them both, both are nice for using.

image

## use cases
- The unlink variant is I think nice if you have list of items and you want to use a subtle unlink icon.
- And the link-2-off is more a "active/direct/more awaring" way of unlinking, maybe less nice to use in a list, but nicer if you "Disconnect" something.

**conclusion** So I think we need to implement both.

**Comment by ericfennis** [comment]
Good one, I will add some.

**Pull request merged**
