### PR TITLE
feat: 'move-horizontal', 'move-vertical', 'move-diagonal', 'mouse-pointer-2'  

### PR DESCRIPTION
**Pull request by ericfennis**
image

### CODE REVIEW

**Comment by jletey** [comment]
I agree with @locness3 here, but it does look like the Figma cursor 🤔

**Comment by ericfennis** [comment]
@jletey haha true. Figma uses this icon design to. It's actually a common cursor/mouse icon design in graphic design programs. Adobe Illustrator and After effects uses it also as the "selection-tool"

**Comment by ericfennis** [comment]
I adjusted the move diagonal icons, the length of the line is now the same as the normal move icons.
image

**Review by locness3 — APPROVED** [review]
I'm not a designer

**Pull request merged**
