### PR TITLE
feat: Add `switch-camera` icon

### PR DESCRIPTION
**Pull request by lscheibel**
Screenshot

image

https://github.com/feathericons/feather/issues/97

### CODE REVIEW

**Comment by ericfennis** [comment]
Maybe we can refactor the current `camera` icon with this "rectangle" body to give the camera 1 px safe zone (Current camera doesn't have the 1 px safe zone).

**Comment by lscheibel** [comment]
image


Would submit PR with this one?

**Comment by jletey** [comment]
@lscheibel That's perfect! Go for it!

**Comment by ericfennis** [comment]
I think this is ready to merge right?

**Pull request merged**
