### PR TITLE
feat: Add separator icons

### PR DESCRIPTION
**Pull request by ericfennis**
Contributes to: [#766](https://github.com/feathericons/feather/issues/766)

image

### CODE REVIEW

**Comment by ericfennis** [comment]
I'm thinking making a second pair more looking like this. 
image

**Comment by ericfennis** [comment]
I added two extra icons, but I don't know if the top ones are fitting the name `separator`? 🤔 
image

**Comment by dgdavid** [comment]
Honestly, the top ones looks a bit weird as "separators". If you ask me, I'd say I prefer the last ones.

**Comment by ericfennis** [comment]
@dgdavid I totally agree.
the top ones look more like `split-panes`.

**Comment by ericfennis** [comment]
I removed the other two, so it is just those two.
image

**Comment by ericfennis** [comment]
@jletey I will try it, to shorten the line. For the brackets I tried, but it looked a bit weird. I think the 2px padding is fits the best.

**Comment by jletey** [comment]
@ericfennis Sounds good, let me know what you come up with!

**Comment by ericfennis** [comment]
@jletey 
image
On the top are the one with shorter lines.

**Comment by ericfennis** [comment]
I implemented the top ones, thanks for the feedback!

**Pull request merged**
