### PR TITLE
feat: Add equal icons and refactor devide icon

### PR DESCRIPTION
**Pull request by ericfennis**
Adds two new icons:
- Equal
- Equal-off

I Adjusted also the devide icon, because it looked weird.

image

### CODE REVIEW

**Review by johnletey — APPROVED** [review]
@ericfennis LGTM

I'm not too certain about the `equal-off` icon. I would think of it more like this:

Screenshot 2020-09-03 at 12 32 35

**Comment by ericfennis** [comment]
@johnletey initial that was my idea to make. But it fitted not well with the other icons.
image

**Comment by johnletey** [comment]
Yeah I agree with that @ericfennis, looks a bit odd 😅

**Comment by ericfennis** [comment]
@locness3 So you mean flip the icon horizontally?

**Comment by locness3** [comment]
Basically yes

**Comment by ericfennis** [comment]
I can't get it right with the slash, maybe just without the spacing? Or what do you think, top or bottom?
image

**Comment by ericfennis** [comment]
According to the discord thread, we have chosen to implement the centered version. I also renamed the icon to `equal-not`, because thats name of the symbol.
image

**Pull request merged**
