### PR TITLE
feat: Add `coins` icon

### PR DESCRIPTION
**Pull request by lscheibel**
Screenshot
image
https://github.com/feathericons/feather/issues/99

### CODE REVIEW

**Comment by ericfennis** [comment]
Love it!

**Comment by ericfennis** [comment]
I don't know if you tried, maybe you can align the angled "one" more on the pixel grid. 
That will look better on low-res devices.
image

**Comment by lscheibel** [comment]
I did but there is just not really any grid to stay on without changing the length of the second 1 too much 😅 However I'd like to suggest an alternative to the current one:

image

I think the top one fits a little better into the current set of icons

**Comment by ericfennis** [comment]
Yeah the top ones are better!

I checked your icon in pixel preview in illustrator.
It looks good better then "angled 1" pixel aligned, so forget what I said. :P

**Comment by lscheibel** [comment]
Alright, will submit the top one 👍 

Yeah I tried a bit but it's just not that many pixels to play with. https://www.figma.com/file/na4b356eGeIHcq7xw99k0J/lscheibel-Feather-Component-Library?node-id=0%3A1 Pixel preview in Figma is `ctrl + p` btw 😄

**Comment by ericfennis** [comment]
Oh didn't know that Figma has also a pixel preview. Good to know!
The top one is the one in this PR right?

**Comment by ericfennis** [comment]
@lscheibel Is this one ready to merge?

**Comment by lscheibel** [comment]
No not yet, gotta push the new one, will hopefully get around to it today

**Comment by lscheibel** [comment]
Okay so I didn't but now it's ready!

**Comment by ericfennis** [comment]
Yes look nice, @lscheibel !

**Pull request merged**
