### PR TITLE
feat: Add `highlighter` icon

### PR DESCRIPTION
**Pull request by lscheibel**
Screenshot
image

https://github.com/feathericons/feather/issues/227

### CODE REVIEW

**Comment by locness3** [comment]
Maybe `highlighter`?

**Comment by lscheibel** [comment]
Maybe just `highlight`? That's also what material icons use

**Comment by jletey** [comment]
@lscheibel Yeah let's go with `highlight`.

**Comment by lscheibel** [comment]
Alright, it's been renamed and ready to merge(?)

**Comment by locness3** [comment]
I'd do highlighter, because highlight is a use-case, when other icons are named with what they represent

**Comment by jletey** [comment]
@locness3 That is a good point.

**Comment by ericfennis** [comment]
Or `marker`? That is what it is right?

**Comment by ericfennis** [comment]
Oh no never mind, a `marker` is also a synonym for `pointer`.

**Comment by lscheibel** [comment]
highlighter it is 😄

**Pull request merged**
