### PR TITLE
feat: Add `library` icon

### PR DESCRIPTION
**Pull request by jletey**
Screenshot 2020-06-25 at 14 48 19

Related: https://github.com/feathericons/feather/pull/647, https://github.com/feathericons/feather/issues/643

### CODE REVIEW

**Comment by locness3** [comment]
:eyes:

**Comment by jletey** [comment]
@locness3 What's that supposed to mean 😅

**Comment by ericfennis** [comment]
Nice, I like the minimalism in this one. Maybe it is an idea, to make also make a variant with a square around it.

And I think it's better to snap those lines on the grid. Or looked that weird?
image

**Comment by dgdavid** [comment]
> also make a variant with a square around it.

I agree.

**Comment by locness3** [comment]
Or a line under it like a shelf

**Comment by jletey** [comment]
Screenshot 2020-06-26 at 19 19 59

tbh that looks a little weird imo @locness3

**Comment by lscheibel** [comment]
I personally like the "shelf" on the bottom. Also I think, we could add the 2px distance between the bars and just scale everything up a little bit. What do you think?

**Comment by jletey** [comment]
What do you think of this?

Screenshot 2020-06-28 at 11 32 10

**Comment by ericfennis** [comment]
Nice I love this one!

**Pull request merged**
