### PR TITLE
feat: Add `languages` icon

### PR DESCRIPTION
**Pull request by ericfennis**
Closes [#938](https://github.com/feathericons/feather/issues/938)
Closes [#455](https://github.com/feathericons/feather/issues/455)
Closes [#36](https://github.com/feathericons/feather/issues/36)

image
image

### CODE REVIEW

**Comment by locness3** [comment]
The two pics do not match :/

**Comment by ericfennis** [comment]
Oh I see, I sended the wrong one. I posted this in the Discord channel. Excuse me!

**Comment by ericfennis** [comment]
haha yeah

**Comment by jletey** [comment]
> I wonder how issues on other repos "close" though 🤔

Yeah me neither 🤔 It's intriguing, guess we'll have to find out 😂

@ericfennis Should this be called `language` or `languages`.

**Comment by ericfennis** [comment]
good question. I seriously don't know. It's presenting two `languages`. But if you work with it maybe `language` fits better. Whats do you think?

**Comment by jletey** [comment]
I think `languages` is fine for now.

**Pull request merged**
