### PR TITLE
Feat: Dashboard/Masonry Icon

### PR DESCRIPTION
**Pull request by ericfennis**
@mittalyashu voila
image

### CODE REVIEW

**Review by locness3 — APPROVED** [review]
We should add a "dashboard" tag to it, btw.

**Comment by ericfennis** [comment]
@locness3 do you think the name "layout-masonry" fits the best?

**Comment by locness3** [comment]
I don't know.

**Comment by ericfennis** [comment]
oke I renamed it to `layout-dashboard`, I think this fits better.

**Pull request merged**
