### PR TITLE
feat: Add `contact` icon

### PR DESCRIPTION
**Pull request by lscheibel**
Hey :wave: was one project away of forking the repo myself. Thanks for doing this :)

Screenshot:

image

### CODE REVIEW

**Comment by locness3** [comment]
Unrelated, but I think the user icons might need a refresh :)

**Comment by jletey** [comment]
@locness3 I completely agree, I'll open an issue with some thoughts 😁

**Comment by jletey** [comment]
@locness3 I completely agree, I'll open an issue with some thoughts 😁

**Comment by locness3** [comment]
yup

**Pull request merged**
