### PR TITLE
feat: Add `screen-share` icons

### LINKED ISSUE #26: Icon request: start/stop sharing screen
Hi there!

First of all, **thank you a lot** for the initiative to, somehow, _moving forward_ the [Feather](https://github.com/feathericons/feather) project. I really hope the effort and result can convince @colebemis  about [his concerns](https://github.com/feathericons/feather/issues/893#issuecomment-617463032) and see both project meet in the near future.

That said, my request is an icon for the "Screen sharing" action in a video conferencing software. Back in April, I was trying to do it but my lack of design / SVG / Figma knowledge didn't allow me to make something presentable. Even after spending quite some hours! Quite frustrating :)

However, just in case it could be helpful, I can tell you that I don't like too much the one [included in the Material Design icons](https://material.io/resources/icons/?icon=screen_share&style=baseline). Maybe, something similar to https://thenounproject.com/search/?q=screen%20share&i=2012801 or https://thenounproject.com/tomekpst/collection/basic-icons/?i=2012799 but based the [Feather/monitor](https://feathericons.com/?query=monitor) could look nice.

On the other hand, using the [Feather/wifi](https://feathericons.com/?query=wifi) or [Feather/rss](https://feathericons.com/?query=rss) icon as part of it instead of the arrow could be confusing because it seems to be more appropriate for an "screen-casting" action, isn't it?

What do you think? Could it be possible to have _feather-style_ icons for start / stop sharing the screen?

Thanks in advance.

## Icon Request

* Icon name: start-screen-sharing, stop-screen-sharing
* Use case: for a video conferencing software
* Screenshots of similar icons:

  |||
  |-|-|
  | Screenshot_2020-06-26 Noun Project | Screenshot_2020-06-26 Noun Project(1) |

### PR DESCRIPTION
**Pull request by jletey**
Screenshot 2020-06-28 at 11 35 20

Closes #26.

### CODE REVIEW

**Comment by dgdavid** [comment]
Wow! You're awesome. I didn't expect to see a pr/proposal right today. Thanks a lot.

If you don't mind, I have some thoughts / suggestions.

* What about placing the up-arrow more centered in the start-screenshare-2? How it looks closing a bit the "gap" in the top border of the monitor?
* Should we use, for consistence, the [Feather/-off](https://feathericons.com/?query=-off) style for the _stop_ versions? I mean, using the same _start_ version but crossed out. 
  
  See the [Feather/mic-off](https://feathericons.com/?query=-off).

  
  Screenshot_2020-06-26 Feather – Simply beautiful open source icons


Have a nice weekend!

**Comment by dgdavid** [comment]
>   * Should we use, for consistence, the [Feather/-off](https://feathericons.com/?query=-off) style for the _stop_ versions? I mean, using the same _start_ version but crossed out.


Also for consistence, `screen-share` and `screen-share-off` could be good names.

**Comment by locness3** [comment]
_discord vibes_

**Comment by jletey** [comment]
> discord vibes

@locness3 That's exactly what I was going for 😁

> `screen-share` and `screen-share-off` could be good names.

Yeah I like that!

> * using the same _start_ version but crossed out.

I personally think the arrow and x are better.

**Comment by lscheibel** [comment]
I really like the ones with the symbol in the corner

**Comment by jletey** [comment]
@lscheibel Same! Those are my favourites. Maybe we should just add those?

**Comment by ericfennis** [comment]
I think the arrow and the x are better too. 
The x presents more "disconnect" I think.

But maybe we can add them in the future as wel!

**Comment by jletey** [comment]
I remove the second variations of the icons for now. They didn't really represent screen-sharing to me. The current ones do though.

If it's okay with everyone think we can merge this 🚀

**Comment by dgdavid** [comment]
> I think the arrow and the x are better too.
> The x presents more "disconnect" I think.
> 

Sure, you both are right. Thinking about "disconnecting" the stream has more sense in that context than "powering it off".

Anyway, I was just suggesting ideas, since rght now it is the only way I can contribute.

> But maybe we can add them in the future as wel!

Let's see ;)

**Comment by jletey** [comment]
> I was just suggesting ideas, since rght now it is the only way I can contribute.

Yeah, we are grateful for your input and ideas, keep it up! 🖤

**Pull request merged**
