### PR TITLE
feat: Add `caret` icons

### PR DESCRIPTION
**Pull request by jletey**
localhost_3000__query=caret (1)

Related: https://github.com/feathericons/feather/issues/600, https://github.com/feathericons/feather/pull/640

### CODE REVIEW

**Comment by locness3** [comment]
Not sure where this would be used

**Comment by jletey** [comment]
> Not sure where this would be used

@locness3 Good point 🤔 Pretty much all of the use-cases that come to mind rn you can use the `chevron` icons 🤷‍♂️

**Comment by ericfennis** [comment]
Nice I like them.
But @locness3 has a point, are those icons not the same use cases as the `chevron` icons ?

**Comment by jletey** [comment]
Fair, I agree with you both - I'll go ahead and close this 😄

**Pull request closed without merging**
